### ISSUE TITLE
No longer works for many files

### ISSUE THREAD

**Issue by shirakia** [altryne/Github-diff-extension#4]
Hi I love this extension for a long time.

Unfortunately, it doesn't work for GitHub new feature lazy loading in Pull Request diff page.
It runs correctly for about 10 files at the top.

Any thoughts for this issue?

**Comment by altryne** [comment]
@shirakia I'm aware and working on a fix, thanks for repoting!

**Comment by shirakia** [comment]
Wonderful! Thanks. I will be waiting.

**Comment by altryne** [comment]
@shirakia hopefully fixed in https://github.com/altryne/Github-diff-extension/tree/v0.1.1
Let me know if you still have issues!

**Comment by shirakia** [comment]
@altryne Thanks! It works really nicely!
